#!/bin/sh



TESTS="enum1.hcc \
       enum1-trailing-comma.hcc \
       enum2.hcc \
       enum3.hcc \
       enum4.hcc \
       enum-typedef.hcc \
       enum-typedef2.hcc \
       enum-typedef-pointer.hcc \
       enum-typedef-pointer2.hcc \
       enum-typedef-bug-1.hcc \
       enum-typedef-bug-2.hcc"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

TESTS="enum-cast-unsigned.hcc enum-cast-unsigned-unsafe.hcc"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -abstract:off "$@" $name 2>&1 | grep -E 'SAFE|UNSAFE'
done

TESTS="enum-negative-safe.c enum-negative-unsafe.c \
       enum-arithmetic-safe.c enum-arithmetic-unsafe.c"

for mode in math ilp32; do
    for name in $TESTS; do
        echo
        echo "$name ($mode)"
        $TRI_CMD -abstract:off "$@" -arithMode:$mode $name 2>&1 | grep -E '^(SAFE|UNSAFE)$'
    done
done

TESTS="enum-wrap-safe.c enum-wrap-unsafe.c"

for name in $TESTS; do
    echo
    echo "$name (ilp32)"
    $TRI_CMD -abstract:off "$@" -arithMode:ilp32 $name 2>&1 | grep -E '^(SAFE|UNSAFE)$'
done
