#!/bin/sh



TESTS="nonlinear2.hcc \
       ../horn-hcc/loop1.hcc \
       ../horn-hcc/loop2.hcc \
       bitwise1.hcc \
       bitwise2.hcc"

for name in $TESTS; do
    echo
    echo $name
    # Clause verification can exhaust memory or time depending on the platform.
    # Keep the warning and result, but normalize the resource-limit diagnostic.
    $TRI_CMD -cex -abstract:off -arithMode:ilp32 "$@" $name 2>&1 | grep -v 'at ' |
        sed -e 's/^Warning: Timeout while verifying clause:$/Warning: Verification of clause was not possible:/' \
            -e '/^Checker said: OutOfMemory$/d'
done

echo
echo MonadicInv.hcc
$TRI_CMD -arithMode:ilp32 "$@" MonadicInv.hcc 2>&1

echo
echo bitwise3.hcc
$TRI_CMD -arithMode:ilp32 "$@" bitwise3.hcc 2>&1

