#!/bin/sh
# Runs the Tricera native image

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname $($pathCmd $0)`
export TRI_PP_PATH="$BASEDIR"

check_binary() {
    if [ ! -f "$BASEDIR/target/native-image/TriCera" ]; then
        echo "Error: Native image binary not found at $BASEDIR/target/native-image/TriCera"
        echo "Please run 'sbt nativeImage' to create it."
        exit 1
    fi
}

check_binary
exec "$BASEDIR/target/native-image/TriCera" "$@"
