#!/bin/sh



TESTS="inc_safe.c \
       inc_unsafe.c \
       mc91_safe.c \
       mc91_unsafe.c \
       incdec_safe.c \
       incdec_unsafe.c \
       getptr_safe.c \
       getptr_unsafe.c \
       assigns_safe.c \
       assigns_unsafe.c \
       maxptr_safe.c \
       maxptr_unsafe.c \
       old_safe.c \
       old_unsafe.c \
       dblptr-assigns_safe.c \
       dblptr-assigns_unsafe.c \
       swap_safe.c \
       swap_unsafe.c \
       structptr_safe.c \
       structptr_unsafe.c \
       nestedptr_safe.c \
       nestedptr_unsafe.c \
       arrstruct_safe.c \
       arrstruct_unsafe.c \
       structarr_safe.c \
       structarr_unsafe.c \
       oldstruct_safe.c \
       oldstruct_unsafe.c \
       namedassert_safe.c \
       namedassert_unsafe.c \
       namedpost_safe.c \
       namedpost_unsafe.c \
       namedpre_safe.c \
       namedpre_unsafe.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD "$@" $name -memsafety -reachsafety
done

