#!/bin/sh

LAZABS=../../tri

TESTS="test1.hcc test2.hcc test3.hcc test4.hcc \
       test-para2.hcc lazy-eval1.hcc \
       jumps.hcc jumps2.hcc jumps3.hcc \
       functions.hcc functions2.hcc extended-decl.hcc \
       inits.hcc inits2.hcc inits3.hcc \
       shadowing.hcc disconnected-assertions.hcc \
       atomic1.hcc atomic2.hcc atomic3.hcc atomic3b.hcc atomic3c.hcc \
       atomic3d.hcc \
       diamond_true-unreach-call1.c unsigned1.hcc \
       literals.c predicates.hcc predicates2.hcc down_true-unreach-call.i.c \
       ternary-bug.c assert-ite-1.c assert-ite-2.c \
       function-in-assume-assert-1-false.c function-in-assume-assert-1-true.c \
       function-in-assume-assert-2-false.c function-in-assume-assert-2-true.c \
       function-in-assume-assert-3-false.c function-in-assume-assert-3-true.c \
       static-local-retention-false.c static-local-retention-true.c \
       static-shadowing-true.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

# disable cex for tests producing unstable output, likely due to different java versions
TESTS="test2b.hcc test2c.hcc test-para1.hcc atomic4.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -abstract:off "$@" $name 2>&1 | grep -v 'at '
done


TESTS="test4.hcc test5.hcc test6.hcc test7.hcc \
       loop1.hcc loop2.hcc locking.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract "$@" $name
done

TESTS="preprocess-1.c "

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cpp "$@" $name
done
