#!/bin/sh

export LAZABS_HOME=../..
export JAR="${LAZABS_HOME}"/target/scala-*/TriCera-assembly-*.jar
export JAVA_OPTS="-Xmx4096m -Xss20000k -cp $JAR"

for mainClass in tricera.concurrency.ParameterisedExamples; do
    echo
    echo $mainClass
    java $JAVA_OPTS $mainClass 2>&1 | grep -v time | grep -v 'ms)' | sed -e 's/Map(.*$//g'
done

