#!/bin/sh

set -e

./rundir horn-hcc-heap "" -assert -dev -t:60
./rundir horn-hcc-array "" -assert -dev -t:60
./rundir horn-bv "" -assert -dev -t:60
./rundir horn-hcc "" -assert -dev -t:60
./rundir horn-hcc-2 "" -assert -dev -t:60
./rundir horn-hcc-pointer "" -assert -dev -t:60
./rundir horn-hcc-struct "" -assert -dev -t:60
./rundir horn-hcc-enum "" -assert -dev -t:60
./rundir horn-contracts "" -assert -dev -t:60
./rundir acsl-contracts "" -assert -t:60
./rundir acsl-standalone "" -m:foo -assert -cex -t:60
./rundir uninterpreted-predicates "" -assert -dev -t:60
#./rundir ParametricEncoder ""
