#!/bin/sh

TESTS="signals1.c \
       signals2.c \
       signals3.c \
       signals4.c \
       progress1.c \
       progress2.c \
       progress3.c \
       progress4.c \
       progress5.c \
       progress6.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -noPP -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

