#!/bin/sh

LAZABS=../../tri

TESTS="out-of-bounds-line1.c out-of-bounds-line2.c out-of-bounds-line3.c out-of-bounds-line4.c dynamic-loop1.c simple-dynamic-array.c simple-global-array.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

MEMTRACKTESTS=""

for name in $MEMTRACKTESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
    # -memtrack can also be added but not required when .yml files are present
done

# this one runs forever with the current encoding
#TESTS="list-002.c"

#for name in $TESTS; do
#    echo
#    echo $name
#    $LAZABS -cex -abstract "$@" $name
#done
