#!/bin/sh



TESTS="pred-hint.c pred-hint-loop.c \
       unint-pred-simple-false.c unint-pred-simple-true.c \
       unint-pred-stack-ptr-unsupported.c unint-pred-simple-ptr-true.c
       unint-pred-unnamed-ptr-arg-bug.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done
