#!/bin/sh



TESTS="anon.hcc assign.hcc assign2.hcc assign-exp-eval-order.hcc assign-illegal.hcc \
       init.hcc loop.hcc nested.hcc typedef.hcc emptyStruct.hcc"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

NOCEXTESTS="race.hcc"
for name in $NOCEXTESTS; do
    echo
    echo $name
    $TRI_CMD -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

