#!/bin/sh

LAZABS=./tri

TESTS="regression-tests/long_double/add_1.c \
       regression-tests/long_double/add_2.c \
       regression-tests/long_double/add_3.c \
       regression-tests/long_double/div_1.c \
       regression-tests/long_double/div_2.c \
       regression-tests/long_double/mul_1.c \
       regression-tests/long_double/mul_2.c \
       regression-tests/long_double/loop_1.c \
       regression-tests/long_double/loop_2.c \
       regression-tests/long_double/sub_1.c \
       regression-tests/long_double/sub_2.c \
       regression-tests/long_double/init_1.c \
       regression-tests/long_double/init_2.c \
       regression-tests/long_double/init_3.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS "$@" $name 2>&1 | grep -v 'at '
done

