#!/bin/sh

LAZABS=../../tri

TESTS="add_1.c \
       add_2.c \
       add_3.c \
       div_1.c \
       div_2.c \
       mul_1.c \
       mul_2.c \
       loop_1.c \
       loop_2.c \
       sub_1.c \
       sub_2.c \
       init_1.c \
       init_2.c \
       init_3.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS "$@" $name 2>&1 | grep -v 'at '
done

