#!/bin/sh

LAZABS=../../tri

TESTS="ext-exist-1-safe.hcc ext-exist-1-unsafe.hcc ext-univ-1-safe.hcc ext-exist-1-unsafe.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done
