#!/bin/sh

LAZABS=../../tri

TESTS="ext-exist-1-true.c \
  ext-exist-1-false.c \
  ext-forall-1-true.c \
  ext-forall-1-false.c \
  ext-forall-2-UB-true.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off -heaparrays -onlyexq "$@" $name 2>&1 | grep -v 'at '
done
