#!/bin/sh



TESTS="block_safe.c \
       block_unsafe.c \
       single_stm_safe.c \
       old_safe.c \
       pre_violated_unsafe.c \
       assigns_unsafe.c \
       nested_safe.c \
       heap_old_safe.c \
       heap_ensures_unsafe.c \
       heap_assigns_safe.c \
       heap_assigns_unsafe.c \
       full_safe.c \
       trailing_warns.c \
       old_struct_safe.c \
       old_struct_unsafe.c \
       ensures_only_safe.c \
       requires_only_safe.c \
       adjacent_rejected.c \
       ghost_inside_safe.c \
       old_global_safe.c \
       early_return_safe.c \
       early_return_unsafe.c \
       break_out_rejected.c \
       function_contract_outer_safe.c \
       goto_inside_safe.c \
       goto_out_rejected.c \
       inferred_safe.c \
       bare_decl_rejected.c \
       nested_in_body_safe.c \
       inner_local_safe.c \
       assigns_nothing_safe.c \
       if_body_safe.c \
       break_inside_safe.c \
       continue_inside_safe.c \
       empty_body_safe.c \
       void_return_safe.c \
       void_return_unsafe.c \
       return_value_in_body_safe.c \
       multi_return_paths_safe.c \
       nested_call_safe.c \
       mixed_kinds_safe.c \
       void_no_return_safe.c \
       assigns_nothing_unsafe.c \
       empty_body_unsafe.c \
       function_contract_outer_unsafe.c \
       mixed_kinds_unsafe.c \
       multi_return_paths_unsafe.c \
       nested_in_body_unsafe.c \
       return_value_in_body_unsafe.c \
       void_no_return_unsafe.c \
       if_body_unsafe.c \
       inferred_unsafe.c \
       inferred_multi_var_safe.c \
       inferred_in_function_safe.c \
       missing_returns_rejected.c \
       returns_only_safe.c \
       returns_only_unsafe.c \
       returns_and_ensures_safe.c \
       returns_and_ensures_unsafe.c \
       modular_safe.c \
       modular_unsafe.c \
       returns_true_safe.c \
       returns_true_unsafe.c \
       no_return_with_returns_clause_safe.c \
       no_return_with_returns_clause_unsafe.c \
       modular_heap_safe.c \
       modular_heap_unsafe.c \
       inferred_heap_safe.c \
       inferred_heap_unsafe.c \
       modular_struct_safe.c \
       modular_struct_unsafe.c \
       inferred_struct_safe.c \
       inferred_struct_unsafe.c \
       inferred_array_safe.c \
       inferred_array_unsafe.c \
       outer_contract_abrupt_return_safe.c \
       outer_contract_abrupt_return_unsafe.c \
       impl_caller_distinguishes_safe.c \
       loose_ambiguous_unsafe.c \
       impl_missing_assigns_unsafe.c \
       status_code_safe.c \
       lookup_or_default_safe.c \
       nested_returns_rejected.c \
       outer_assigns_violated_unsafe.c \
       outer_assigns_consistent_safe.c \
       heap_abrupt_return_safe.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD "$@" $name 2>&1 | grep -v 'at ' | grep -v 'Warning: no `assigns`'
done
