#!/bin/sh



TESTS="stmt_contract_block_safe.c \
       stmt_contract_block_unsafe.c \
       stmt_contract_single_stm_safe.c \
       stmt_contract_old_safe.c \
       stmt_contract_pre_violated_unsafe.c \
       stmt_contract_assigns_unsafe.c \
       stmt_contract_nested_safe.c \
       stmt_contract_heap_old_safe.c \
       stmt_contract_heap_ensures_unsafe.c \
       stmt_contract_heap_assigns_safe.c \
       stmt_contract_heap_assigns_unsafe.c \
       stmt_contract_full_safe.c \
       stmt_contract_trailing_warns.c \
       stmt_contract_old_struct_safe.c \
       stmt_contract_old_struct_unsafe.c \
       stmt_contract_ensures_only_safe.c \
       stmt_contract_requires_only_safe.c \
       stmt_contract_adjacent_rejected.c \
       stmt_contract_ghost_inside_safe.c \
       stmt_contract_old_global_safe.c \
       stmt_contract_early_return_safe.c \
       stmt_contract_early_return_unsafe.c \
       stmt_contract_break_out_rejected.c \
       stmt_contract_function_contract_outer_safe.c \
       stmt_contract_goto_inside_safe.c \
       stmt_contract_goto_out_rejected.c \
       stmt_contract_inferred_safe.c \
       stmt_contract_bare_decl_rejected.c \
       stmt_contract_nested_in_body_safe.c \
       stmt_contract_inner_local_safe.c \
       stmt_contract_assigns_nothing_safe.c \
       stmt_contract_if_body_safe.c \
       stmt_contract_break_inside_safe.c \
       stmt_contract_continue_inside_safe.c \
       stmt_contract_empty_body_safe.c \
       stmt_contract_void_return_safe.c \
       stmt_contract_void_return_unsafe.c \
       stmt_contract_return_value_in_body_safe.c \
       stmt_contract_multi_return_paths_safe.c \
       stmt_contract_nested_call_safe.c \
       stmt_contract_mixed_kinds_safe.c \
       stmt_contract_void_no_return_safe.c \
       stmt_contract_assigns_nothing_unsafe.c \
       stmt_contract_empty_body_unsafe.c \
       stmt_contract_function_contract_outer_unsafe.c \
       stmt_contract_mixed_kinds_unsafe.c \
       stmt_contract_multi_return_paths_unsafe.c \
       stmt_contract_nested_in_body_unsafe.c \
       stmt_contract_return_value_in_body_unsafe.c \
       stmt_contract_void_no_return_unsafe.c \
       stmt_contract_if_body_unsafe.c \
       stmt_contract_inferred_unsafe.c \
       stmt_contract_inferred_multi_var_safe.c \
       stmt_contract_inferred_in_function_safe.c \
       stmt_contract_missing_returns_rejected.c \
       stmt_contract_returns_only_safe.c \
       stmt_contract_returns_only_unsafe.c \
       stmt_contract_returns_and_ensures_safe.c \
       stmt_contract_returns_and_ensures_unsafe.c \
       stmt_contract_modular_safe.c \
       stmt_contract_modular_unsafe.c \
       stmt_contract_returns_true_safe.c \
       stmt_contract_returns_true_unsafe.c \
       stmt_contract_no_return_with_returns_clause_safe.c \
       stmt_contract_no_return_with_returns_clause_unsafe.c \
       stmt_contract_modular_heap_safe.c \
       stmt_contract_modular_heap_unsafe.c \
       stmt_contract_inferred_heap_safe.c \
       stmt_contract_inferred_heap_unsafe.c \
       stmt_contract_modular_struct_safe.c \
       stmt_contract_modular_struct_unsafe.c \
       stmt_contract_inferred_struct_safe.c \
       stmt_contract_inferred_struct_unsafe.c \
       stmt_contract_inferred_array_safe.c \
       stmt_contract_inferred_array_unsafe.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD "$@" $name 2>&1 | grep -v 'at '
done
