#!/bin/sh



TESTS="simple-invariant-false.c simple-invariant-true.c \
       simple-invariant-false.c simple-loop-invariant-true.c \
       simple-loop-invariant-false.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -cex "$@" $name 2>&1 | grep -v 'at '
done
