#!/bin/sh

LAZABS=../../tri

TESTS="contract1.hcc  \
       contract2.hcc  \
       contract3.hcc  \
       contract4.hcc  \
       contract5.hcc  \
       contract6.hcc  \
       contract7.hcc  \
       contract8.hcc  \
       contract9.hcc  \
       contract10.hcc \
       contract11.hcc \
       contract12.hcc \
       contract13.hcc \
       contract14.hcc \
       contract15.hcc \
       contract16.hcc \
       contract17.hcc \
       contract18.hcc \
       contract19.hcc \
       contract20.hcc \
       contract21.hcc \
       contract22.hcc \
       contract23.hcc \
       contract24.hcc \
       contract25.hcc \
       contract26.hcc \
       contract27.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS "$@" $name 2>&1 | grep -v 'at '
done

