#!/bin/sh



TESTS="contract1.hcc  \
       contract2.hcc  \
       contract3.hcc  \
       contract4.hcc  \
       contract5.hcc  \
       contract6.hcc  \
       contract7.hcc  \
       contract8.hcc  \
       contract9.hcc  \
       contract10.hcc \
       contract11.hcc \
       contract12.hcc \
       contract13.hcc \
       contract14.hcc \
       contract15.hcc \
       contract16.hcc \
       contract17.hcc \
       contract18.hcc \
       contract19.hcc \
       contract20.hcc \
       contract21.hcc \
       contract22.hcc \
       contract23.hcc \
       contract24.hcc \
       contract25.hcc \
       contract26.hcc \
       contract27.hcc \
       global-post-safe.hcc \
       global-post-unsafe.hcc \
       global-old-safe.hcc \
       global-old-unsafe.hcc \
       global-at-safe.hcc \
       global-at-unsafe.hcc \
       global-from-safe.hcc \
       global-from-unsafe.hcc \
       quant-forall-safe.hcc \
       quant-forall-unsafe.hcc \
       quant-exists-safe.hcc \
       cast-safe.hcc \
       cast-unsafe.hcc \
       cast-modular-safe.hcc \
       separated-safe.hcc \
       separated-unsafe.hcc \
       separated-three-safe.hcc \
       global-array-contract-safe.hcc \
       valid-array-safe.hcc \
       valid-array-unsafe.hcc \
       valid-array-ensures-safe.hcc \
       typedef-annotation-safe.hcc \
       from-warning-body.hcc \
       from-warning-bodyless.hcc \
       valid-read-safe.hcc \
       valid-read-unsafe.hcc \
       predicate-standalone-safe.hcc \
       predicate-standalone-unsafe.hcc \
       enum-constant-contract-safe.hcc \
       enum-constant-contract-unsafe.hcc \
       enum-constant-assert-safe.hcc \
       enum-constant-assert-unsafe.hcc \
       assigns-array-safe.hcc \
       assigns-array-unsafe.hcc \
       global-assigns-frame-safe.hcc \
       global-assigns-frame-unsafe.hcc \
       global-void-return-safe.hcc \
       global-result-unsafe.hcc \
       global-local-shadow-unsafe.hcc \
       global-param-safe.hcc \
       struct-field-access-1-true.hcc \
       struct-field-access-2-false.hcc \
       struct-field-access-3-true.hcc \
       struct-field-access-4-false.hcc"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD "$@" $name 2>&1 | grep -v 'at '
done

