#!/bin/sh



TESTS="basic.hcc fields.hcc fields-nested.hcc struct-pointer.hcc struct-pointer2.hcc unary.hcc unary-struct.hcc unary-struct-nested.hcc list-init.hcc cast-stack-heap-01.c cast-stack-heap-field-safe.c cast-stack-heap-field-unsafe.c ptrptr-bug-1.c  ptrptr-bug-2.c ptr-to-int-cast.c stack-ptr-fun-ret.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

