#!/bin/sh



TESTS="ghost_global_safe.c \
       ghost_block_form_safe.c \
       ghost_with_init_safe.c \
       ghost_local_decl_safe.c \
       ghost_shadowing_unaffected_safe.c \
       ghost_multi_decl_safe.c \
       ghost_multi_stmt_safe.c \
       ghost_interleaved_safe.c \
       ghost_separate_lines_safe.c \
       ghost_acsl_assert_safe.c \
       ghost_c_assert_safe.c \
       ghost_c_assume_safe.c \
       ghost_pointer_assign_safe.c \
       ghost_struct_field_safe.c \
       ghost_control_flow_if_safe.c \
       ghost_while_loop_safe.c \
       ghost_wrong_contract_unsafe.c \
       ghost_multi_stmt_unsafe.c \
       ghost_acsl_assert_unsafe.c \
       ghost_c_assert_unsafe.c \
       ghost_pointer_assign_unsafe.c \
       ghost_struct_field_unsafe.c \
       ghost_control_flow_if_unsafe.c \
       ghost_not_visible_in_c.c \
       ghost_c_other_expr_rejected.c \
       ghost_name_clash_global.c \
       ghost_name_clash_local.c \
       ghost_integer_type_safe.c \
       ghost_boolean_type_safe.c \
       ghost_multi_line_integer_safe.c \
       ghost_writes_non_ghost_rejected.c \
       ghost_writes_non_ghost_field_rejected.c \
       ghost_identifier_integer_outside_safe.c"

for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD "$@" $name 2>&1 | grep -v 'at '
done
