#!/bin/sh

LAZABS=../../tri

TESTS="list-001.c list-001-fail.c list-002-fail.c mutually-referential-structs.c mutually-referential-structs-fail.c mutually-referential-structs-unsafe.c simple-struct.c simple-struct-2.c simple-struct-fail.c swap-1.c swap-1-fail.c swap-2.c swap-2-fail.c swap-3.c simple-arith.c typecastUnsafe-001.c typecastSafe-001.c illegal-access-001.c illegal-access-002.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

# this one runs forever with the current encoding
#TESTS="list-002.c"

#for name in $TESTS; do
#    echo
#    echo $name
#    $LAZABS -cex -abstract "$@" $name
#done
