#!/bin/sh

LAZABS=../../tri

TESTS="list-001.c list-001-fail.c list-002-fail.c mutually-referential-structs.c mutually-referential-structs-fail.c mutually-referential-structs-unsafe.c simple-struct.c simple-struct-2.c simple-struct-fail.c swap-1.c swap-1-fail.c swap-2.c swap-2-fail.c swap-3.c simple-arith.c typecastUnsafe-001.c typecastSafe-001.c illegal-access-001.c illegal-access-002.c postop.c postop-struct.c preop.c preop-struct.c opassign.c opassign-struct.c unsafe-access-001.c stackptr-to-heapptr.c free-1-unsafe.c free-2-nondet-unsafe.c free-3-safe.c free-4-unsafe.c struct-ptrfield-1.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

MEMTRACKTESTS="memtrack-01.c memtrack-02.c memtrack-03.c memtrack-04.c memtrack-05.c memtrack-06.c "

for name in $MEMTRACKTESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
    # -memtrack can also be added but not required when .yml files are present
done

# this one runs forever with the current encoding
#TESTS="list-002.c"

#for name in $TESTS; do
#    echo
#    echo $name
#    $LAZABS -cex -abstract "$@" $name
#done
