#!/bin/sh

LAZABS=../../tri

TESTS="contract1.hcc \
       contract2.hcc \
       contract2b.hcc \
       contract3.hcc \
       takeuchi.hcc  \
       assert.hcc \
       fib.hcc \
       stackptr.hcc \
       struct-name-bug.hcc \
       stackptr-multi-arg.c \
       stackptr-nested-calls.c \
       stackptr-recursion.c \
       stackptr-retvalue.c"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -acsl "$@" $name 2>&1 | grep -v 'at '
done

TESTS="stackptr-custom-entry.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -acsl -m:entryPoint "$@" $name 2>&1 | grep -v 'at '
done