#!/bin/sh

LAZABS=../../tri

TESTS="contract1.hcc \
       contract2.hcc \
       contract2b.hcc \
       contract3.hcc \
       takeuchi.hcc  \
       assert.hcc \
       fib.hcc \
       stackptr.hcc"

for name in $TESTS; do
    echo
    echo $name
    { $LAZABS -cex -acsl "$@" $name > >(tee stdout.log) 2> >(grep ' Error' >&2); }
done

