#!/bin/sh

LAZABS=./tri

TESTS="regression-tests/float/add_1.c \
       regression-tests/float/add_2.c \
       regression-tests/float/add_3.c \
       regression-tests/float/div_1.c \
       regression-tests/float/div_2.c \
       regression-tests/float/init_1.c \
       regression-tests/float/init_2.c \
       regression-tests/float/loop_1.c \
       regression-tests/float/loop_2.c \
       regression-tests/float/mul_1.c \
       regression-tests/float/mul_2.c \
       regression-tests/float/sub_1.c \
       regression-tests/float/sub_2.c "

for name in $TESTS; do
    echo
    echo $name
    $LAZABS "$@" $name 2>&1 | grep -v 'at '
done

